FROM php:7.1-alpine
MAINTAINER drupal-docker

VOLUME /var/www/html
WORKDIR /var/www/html

RUN apk add --no-cache --virtual .dd-build-deps libpng-dev libjpeg-turbo-dev postgresql-dev libxml2-dev $PHPIZE_DEPS \
   && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
   && docker-php-ext-install gd mbstring pdo pdo_mysql pdo_pgsql zip \
   && docker-php-ext-install opcache bcmath soap \
   && pecl install redis-3.1.1 \
   && docker-php-ext-enable redis \
   && curl -sS https://getcomposer.org/installer | php \
   && mv composer.phar /usr/local/bin/composer \
   && echo "export PATH=~/.composer/vendor/bin:\$PATH" >> ~/.bash_profile \
   && apk add --no-cache sudo git libpng libjpeg libpq libxml2 mysql-client openssh-client rsync \
   && apk del .dd-build-deps

COPY drupal-*.ini /usr/local/etc/php/conf.d/
COPY cli/drupal-*.ini /usr/local/etc/php/conf.d/
