FROM drupaldocker/php:7.1-alpine-fpm
MAINTAINER drupal-docker

RUN apk add --no-cache --virtual .dd-build-deps $PHPIZE_DEPS \
 && pecl install xdebug-2.6.0beta1 \
 && docker-php-ext-enable xdebug \
 && apk del .dd-build-deps

COPY drupal-*.ini /usr/local/etc/php/conf.d/
