FROM drupaldocker/php:8.1-cli-2.x
MAINTAINER drupal-docker

RUN apk add --no-cache --virtual .dd-build-deps linux-headers $PHPIZE_DEPS \
 && pecl install xdebug-3.2.0 \
 && docker-php-ext-enable xdebug \
 && apk del .dd-build-deps

COPY drupal-*.ini /usr/local/etc/php/conf.d/
