FROM php:8.0-alpine
MAINTAINER drupal-docker

WORKDIR /var/www/html

RUN apk add --no-cache --virtual .dd-build-deps libpng-dev freetype-dev libjpeg-turbo-dev postgresql-dev libxml2-dev libzip-dev oniguruma-dev $PHPIZE_DEPS \
  && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
  && docker-php-ext-install gd mbstring pdo_mysql pdo_pgsql zip \
  && docker-php-ext-install opcache bcmath soap \
  && pecl install redis-5.3.7 \
  && docker-php-ext-enable redis \
  && curl -sS https://getcomposer.org/installer | php \
  && mv composer.phar /usr/local/bin/composer \
  && curl -L -o drush.phar https://github.com/drush-ops/drush-launcher/releases/download/0.10.1/drush.phar \
  && chmod +x drush.phar \
  && mv drush.phar /usr/local/bin/drush \
  && curl -L -o drupal.phar https://drupalconsole.com/installer \
  && chmod +x drupal.phar \
  && mv drupal.phar /usr/local/bin/drupal \
  && echo "export PATH=~/.composer/vendor/bin:\$PATH" >> ~/.bash_profile \
  && apk add --no-cache sudo git libpng freetype libjpeg libpq libxml2 mysql-client openssh-client rsync patch libzip \
  && apk del .dd-build-deps

COPY drupal-*.ini /usr/local/etc/php/conf.d/
COPY cli/drupal-*.ini /usr/local/etc/php/conf.d/
