FROM php:8.0-fpm-alpine
MAINTAINER drupal-docker

RUN apk add --no-cache --virtual .dd-build-deps libpng-dev freetype-dev libjpeg-turbo-dev postgresql-dev libxml2-dev libzip-dev oniguruma-dev $PHPIZE_DEPS \
   && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
   && docker-php-ext-install gd mbstring pdo_mysql pdo_pgsql zip \
   && docker-php-ext-install opcache bcmath soap \
   && pecl install redis-5.3.7 \
   && docker-php-ext-enable redis \
   && apk add --no-cache libpng freetype libjpeg libpq libxml2 libzip \
   && apk del .dd-build-deps

COPY drupal-*.ini /usr/local/etc/php/conf.d/
