FROM php:5.6-fpm-alpine
MAINTAINER drupal-docker

VOLUME /var/www/html

RUN apk add --no-cache --virtual .dd-build-deps libpng-dev libjpeg-turbo-dev postgresql-dev $PHPIZE_DEPS \
   && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
   && docker-php-ext-install gd mbstring pdo pdo_mysql pdo_pgsql zip \
   && docker-php-ext-install opcache bcmath \
   && pecl install redis-2.2.8 \
   && docker-php-ext-enable redis \
   && apk add --no-cache libpng libjpeg libpq \
   && apk del .dd-build-deps

COPY drupal-*.ini /usr/local/etc/php/conf.d/
