
FROM php:7.0-fpm
MAINTAINER drupal-docker

VOLUME /var/www/html

RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev libpq-dev libxml2-dev \
	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
	&& docker-php-ext-install gd mbstring pdo_mysql pdo_pgsql zip \
	&& docker-php-ext-install opcache bcmath soap \
  && pecl install redis-3.1.1 \
  && docker-php-ext-enable redis \
	&& rm -rf /var/lib/apt/lists/*

COPY drupal-*.ini /usr/local/etc/php/conf.d/
