FROM php:7.0-apache
MAINTAINER drupal-docker

VOLUME /var/www/html

RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev libpq-dev \
	&& docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
	&& docker-php-ext-install gd mbstring pdo pdo_mysql zip \
	&& docker-php-ext-install opcache \
  && pecl install redis-3.0.0 \
  && docker-php-ext-enable redis \
	&& a2enmod rewrite \
	&& rm -rf /var/lib/apt/lists/*

# Compile and install uploadprogress #
RUN git clone https://github.com/Jan-E/uploadprogress.git /tmp/php-uploadprogress && \
        cd /tmp/php-uploadprogress && \
        phpize && \
        ./configure --prefix=/usr && \
        make && \
        make install && \
        echo 'extension=uploadprogress.so' > $PHP_INI_DIR/conf.d/uploadprogress.ini && \
        rm -rf /tmp/*

COPY drupal-*.ini /usr/local/etc/php/conf.d/
